org.example.bookstore.handlers=java.util.logging.FileHandler
org.example.bookstore.models.Book.handlers=java.util.logging.ConsoleHandler
org.example.bookstore.stores.BookStore.handlers=java.util.logging.ConsoleHandler
java.util.logging.FileHandler.pattern=bookstore.log
java.util.logging.FileHandler.formatter=java.util.logging.SimpleFormatter
java.util.logging.ConsoleHandler.level=WARNING
